# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

  steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with: node-version: '16'

    -name: Cache dependencies
    id: cache
      uses: actions/cache@v3
      with:
        path: ~/.node_modules
        key: npm-${{ hashFiles('package-lock.json') }}
        

    -name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'

    - run: npm ci --ignore-scripts
    - run: pm2 restart ecosystem.config.js

